package pt.isep.metayaml.inference.rules;

import pt.isep.metayaml.model.InferredMetamodel;
import pt.isep.metayaml.model.MetaClass;
import pt.isep.metayaml.model.MetaReference;

import java.util.ArrayList;
import java.util.Set;

/**
 * R4 — Pass-through elimination rule.
 *
 * <p>A "pass-through" class has no attributes and exactly one containment
 * reference with {@code many=true}. These are intermediate container classes
 * generated by named map containers (e.g., {@code Jobs} exists only to hold
 * {@code Job} instances).
 *
 * <p>This rule collapses such classes by rewiring every parent reference
 * that pointed to the pass-through directly to the child, preserving the
 * parent's reference name and setting {@code many=true}.
 *
 * <p>Example:
 * <pre>
 *   GithubActions --[jobs]--> Jobs --[job]--> Job [1..*]
 *   becomes:
 *   GithubActions --[jobs]--> Job [1..*]
 * </pre>
 */
public class R4_PassThroughEliminationRule implements IRefinementRule {

    // Event sub-classes of On that must not be eliminated even with a single reference
    private static final Set<String> PROTECTED_NAMES = Set.of("Workflow_call", "Workflow_dispatch");

    @Override
    public void apply(InferredMetamodel metamodel) {
        boolean changed = true;
        while (changed) {
            changed = tryEliminate(metamodel);
        }
    }

    private boolean tryEliminate(InferredMetamodel metamodel) {
        for (MetaClass candidate : new ArrayList<>(metamodel.getClasses())) {
            if (!isPassThrough(candidate)) continue;

            MetaReference inner = candidate.getReferences().get(0);
            MetaClass child = inner.getTarget();

            for (MetaClass cls : metamodel.getClasses()) {
                for (MetaReference ref : cls.getReferences()) {
                    if (ref.getTarget() == candidate) {
                        ref.setTarget(child);
                        ref.setMany(true);
                        if (inner.isOptional()) ref.setOptional(true);
                    }
                }
            }

            metamodel.removeClass(candidate);
            System.out.printf("[INFO] R4: eliminated pass-through '%s' -> '%s'%n",
                    candidate.getName(), child.getName());
            return true;
        }
        return false;
    }

    private boolean isPassThrough(MetaClass cls) {
        return !PROTECTED_NAMES.contains(cls.getName())
                && cls.getAttributes().isEmpty()
                && cls.getReferences().size() == 1
                && cls.getReferences().get(0).isMany()
                && cls.getReferences().get(0).isContainment();
    }
}